"""empty message

Revision ID: 13864f678113
Revises: 7f9e329915b8
Create Date: 2020-06-08 16:59:24.632917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13864f678113'
down_revision = '7f9e329915b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride fare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentLocation', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride fare')
    # ### end Alembic commands ###
