"""empty message

Revision ID: 14ee342ef58c
Revises: 13864f678113
Create Date: 2020-06-10 11:31:43.520547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ee342ef58c'
down_revision = '13864f678113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('type_of_user', sa.String(), nullable=True))
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'typeOfUser')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('typeOfUser', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'type_of_user')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
